### ISSUE TITLE
How to get train datasets

### ISSUE THREAD

**Issue by flybiubiu** [IMAC-projects/NSRR-PyTorch#3]
Thx author!This is a nice project

**Comment by guillaume-haerinck** [comment]
Thanks ! It is still a work in progress so the network is not finished yet (it is supposed to be in a few weeks). You can generate a dataset from [this Unity project](https://gitlab.com/piptouque/unity_ml_dataset).  We created a simple one with a moving cube, it is available [here](https://1drv.ms/u/s!At-_rzmEBExXt2-s77hQnQclIvqz?e=crUhhA)
